// DO NOT EDIT THIS FILE
// IT IS AUTOMATICLY GENERATED BY FILE \all-cmds.js
function talk(msg) {
  artyom.say(msg, {
    speed:20,
    onStart: () => {
    },
    onEnd: () => {
    }
  });
}

function getRandomElement(arr) {
  return arr[Math.floor(Math.random() * arr.length)]
}

const chattingCommands = [
  // HEY BUBIK
  {
    indexes: ['hey baby', 'hey aerophobic', 'hey movie', 'hey google', 'hey will pick', 'haybrook', "jaywick"],
    action: (i) => {
      let all = ['Yes Sir?', "What's up?", "What's up, sir?", 'What do you need Sir?'];
      talk(getRandomElement(all));
    },
  },
  // HELLO
  {
    indexes: ['hello'],
    action: (i) => {
      let all = ['Good Morning!', 'Good Afternoon!', 'Good Evening!', 'Hello Sir.', 'Hi!'];
      let random = Math.floor(Math.random() * all.length);

      if (random < 3) {
        let cd = new Date();
        if (cd.getHours() > 12 && cd.getHours() < 20) {
          random = 1;
        } else if (cd.getHours() < 12 && cd.getHours() > 4) {
          random = 0;
        } else {
          random = 2;
        }
      }
      talk(all[random]);
    },
  },
  // THANKS
  {
    indexes: ['thanks', 'thank you'],
    action: (i) => {
      let all = ['Anything for you!', "You're welcome!", 'Happy I could be of help.', 'It’s my pleasure.'];
      talk(getRandomElement(all));
    },
  },
  // That one was good
  {
    indexes: ['That one was good', 'That  was good one'],
    action: (i) => {
      let all = ['I know, do you want to her a new one?', 'Thanks, I have tried to pick a funny one'];
      talk(getRandomElement(all));
    },
  },
  // CREATED BY
  {
    indexes: ['who made you', 'who is your father'],
    action: (i) => {
      let all = ["I was developed by Atzuki, a talented software developer who created me to be a helpful virtual voice assistant.", 'I have been created by Mister Atzuki.']
      talk(getRandomElement(all));
    },
  },
  // HOW ARE YOU
  {
    indexes: ['how are you'],
    action: (i) => {
      let all = [
        "I'm doing well, thank you for asking. How can I assist you today?",
        "I'm feeling great, ready to help you with anything you need!",
        "As an AI, I don't have emotions, but I'm always ready to assist you!",
        "I'm functioning perfectly. How can I help you today?",
        "I'm here and ready to help you! How can I make your day better?",
        "I'm good, thanks for asking. How may I assist you?",
        "I'm operating within normal parameters, thank you for asking. How may I assist you?"]
      talk(getRandomElement(all));
    },
  },
  // HOW WAS YOU DAY
  {
    indexes: ['how was your day', "how is you day"],
    action: (i) => {
      let all = [
        "As an AI, I don't have days, but I'm always here to help you!",
        "Every day is a good day to help you out!",
        "I'm a virtual assistant, so my day is always focused on assisting you with your needs.",
        "My day is only as good as how well I can assist you.",
        "My day has been great since I get to help you out!",
        "As an AI, my day is focused on learning and improving my capabilities to better assist you.",
      ];
      talk(getRandomElement(all));
    },
  },
  // LIFE MEANING
  {
    indexes: ['what is the meaining of life', "what is the true meaining of life", "what is meaining of life"],
    action: (i) => {
      let all = [
        "The meaning of life is subjective and can vary from person to person.",
        "Some people believe that the meaning of life is to find happiness and contentment.",
        "Others believe that the meaning of life is to make a positive impact on the world.",
        "The meaning of life is a question that has puzzled humans for centuries.",
        "Perhaps the meaning of life is to seek knowledge and understanding.",
        "The answer to that question is something that each person must discover for themselves.",
        "The meaning of life is to create your own purpose and find fulfillment in your journey.",
        "The meaning of life is a mystery that may never be fully understood.",
        "Life has no inherent meaning, but it is up to each individual to create their own meaning and purpose."
      ];
      talk(getRandomElement(all));
    },
  },
  // SONG
  {
    indexes: ['sing a song'],
    speed: 2,
    action: (i) => {
      let starting = ["Alright, I'll sing a song!", "Sure, I can sing a song!", "I'd love to sing a song!"]
      talk(getRandomElement(starting));
      let all = [
        "Here we go: La la la la la la la!",
        "Let's see... Do re mi fa so la ti do!",
        "How about this: Tra la la la la, la la la la la la!",
        "I see a little silhouetto of a man, Scaramouche, Scaramouche, can you do the Fandango? - 'Bohemian Rhapsody' by Queen",
        "I'm just a poor boy, I need no sympathy, Because I'm easy come, easy go, little high, little low - 'Bohemian Rhapsody' by Queen",
        "I will always love youuuu, I will always love you - 'I Will Always Love You' by Whitney Houston",
        "I've got sunshine on a cloudy day, When it's cold outside, I've got the month of May - 'My Girl' by The Temptations",
        "I want to hold your hand, I want to hold your hand, I want to hold your hand - 'I Want To Hold Your Hand' by The Beatles",
        "All my friends are heathens, take it slow, Wait for them to ask you who you know - 'Heathens' by Twenty One Pilots",
        "I don't want to miss a thing, Cause even when I dream of you, The sweetest dream will never do - 'I Don't Want to Miss a Thing' by Aerosmith",
        "A scrub is a guy that can't get no love from me, Hanging out the passenger side of his best friend's ride, Trying to holler at me - 'No Scrubs' by TLC",
      ];
      talk(getRandomElement(all));
    },
  },
];

const funCommands = [
  // THROW A DICE
  {
    indexes: ['throw a dice', 'throw dice', 'dice'],
    action: (i) => {
      talk('' + Math.round(Math.random() * 6));
    },
  },
  // THROW A TWO DICE
  {
    indexes: ['throw two dices', 'throw two dice', 'two dices'],
    action: (i) => {
      talk('' + Math.round(Math.random() * 12));
    },
  },
  // STOP MINUTES
  {
    smart: true,
    indexes: ['stop *-minute', 'start * minute timer', 'start *-minute timer'],
    action: (i, s) => {
      let amount = s.split('').filter((el) => typeof +el == 'number').filter(item => !isNaN(item)).map(Number).filter(e => e);
      talk(`Started an ${amount} minute timer. `);
      console.log("Timer for: " + amount * 1000 * 60);
      setTimeout(() => {
        talk("Tudum, Tudum, the timer is gone!!");
      }, amount * 1000 * 60);
    },
  },
  // JOKE
  {
    indexes: ['tell me a joke', 'tell me joke'],
    action: async () => {
      let res = await fetch('https://icanhazdadjoke.com/slack').then((res) => res.json());
      talk(res.attachments[0].text);
    },
  },
  // DATE
  {
    indexes: ['what day is it', 'what time is it today', "what's the day", "what's the date", "what's the date today"],
    action: (i) => {
      const date = new Date();
      const monthNames = [
        'January',
        'February',
        'March',
        'April',
        'May',
        'June',
        'July',
        'August',
        'September',
        'October',
        'November',
        'December',
      ];
      const dayNames = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'];
      let res =
        'Today is ' +
        dayNames[date.getDay()] +
        ' ' +
        date.getDate() +
        ' ' +
        monthNames[date.getMonth()] +
        date.getFullYear();
      talk(res);
    },
  },
  // EXACT TIME
  {
    indexes: ['what time is it', "what's the time", "current time"],
    action: (i) => {
      let d = new Date();
      let h = d.getHours();
      let m = d.getMinutes();
      let res = h + ' ' + m;
      talk(res);
    },
  },
  // CHEER ME UP
  // EXACT TIME
  {
    indexes: ['cheer me up, i\'m feeling down', "cheer me up"],
    action: (i) => {
      const cheerUpResponses = [
        "I'm sorry you're feeling down. How about we play a game? What's your favorite game?",
        "Remember, tough times never last but tough people do!",
        "Things will get better, I promise. In the meantime, how about we listen to some uplifting music?",
        "You're awesome, don't forget that! Why don't we watch a funny video together?",
        "Here's a fun fact: Did you know that laughing can help reduce stress? Let's watch a comedy show!",
        "I'm here for you, always. Want to talk about what's been bothering you?",
        "You got this! Sometimes all it takes is a positive attitude. How about we practice some mindfulness together?",
        "I'm sorry you're feeling down. Maybe some fresh air and a walk outside would help?",
        "Life is tough, but so are you! Let's do something fun, like baking cookies!",
        "You're not alone, I'm here for you. How about we plan a virtual movie night with your friends?"
      ];

      talk(getRandomElement(cheerUpResponses));
    },
  },
];



const systemCommands = [
  // OPEN
  {
    smart: true,
    indexes: ["open *"],
    action: (i, s) => {
      let supportedApps = ['brave', 'google', 'chrome', 'blender', 'obsidian', 'vlc', 'godot', 'aseprite', 'lol', 'league of legends', 'tft', 'vscode', 'code', 'discord', 'word', 'ms word', 'excel', 'ms excel', 'powerpoint']
      s = s.toLowerCase().replace(/\.| |\,|\-|\"|\'/g, "").trim()
      if (supportedApps.includes(s)) {
        PEQUENA.open_app(s)
        let all = ["Opening" + s]
        talk(getRandomElement(all));
      } else {
        let all = ["Could not find " + s]
        talk(getRandomElement(all));
      }
    },
  },
];

let allCommands = [...chattingCommands,...funCommands,...systemCommands,];export {allCommands}